logs:
  - name: node01
    log_path: "C:\\Users\\ajnab\\AppData\\Roaming\\Spacemesh\\spacemesh-log-7c8cef2b.txt"
    log_type: 'default'
output: 'D:\\Code\\potatoparse' # Delete this if you do not wish to output the events to CSV